NAME: rotation
MODEL:
  LANDMARKS_DIM: 136
  ROTATION_NUM_LAYERS: 3
  CRITIC_NUM_LAYERS: 4
TRAIN:
  FINETUNE_CHECKPOINT: "checkpts/alae.pt"
  CENTER_IDENTITY_SIZE: 4
  CENTER_IDENTITY_STEP: 32
  ROTATION_BATCH_SIZE: 8
  LOGDIR: "./logs/"
  N_EPOCHS: 1000
  CHECKPOINT_SAVE_STEP: 250
